version: 2.1
executors:
  java-8:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx3200m
  android:
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
commands:
  restore_workspace:
    steps:
      - attach_workspace:
          at: .
  gradle_cache:
    description: "Restore gradle caches"
    steps:
      - restore_cache:
          keys:
            - v1-gradlew-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradlew-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
jobs:
  checkout:
    executor: java-8
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    executor: java-8
    steps:
      - restore_workspace
      - gradle_cache
      - run: ./gradlew assemble
      - persist_to_workspace:
          root: .
          paths:
            - .gradle
            - lib/build
            - plugin/build
            - processor/build
  assemble_samples:
    executor: android
    steps:
      - restore_workspace
      - gradle_cache
      - run: cd sample && ./gradlew assembleAndroidTest
  test:
    executor: java-8
    steps:
      - restore_workspace
      - gradle_cache
      - run: ./gradlew test
  static_analysis:
    executor: java-8
    steps:
      - restore_workspace
      - gradle_cache
      - run: ./gradlew detekt
  unwrap_gpg_key:
    executor: java-8
    steps:
      - restore_workspace
      - run: echo '$GPG_KEY_CONTENTS' | base64 -d > '$SIGNING_SECRET_KEY_RING_FILE'"
       - persist_to_workspace:
           root: .
           paths:
             - $SIGNING_SECRET_KEY_RING_FILE
  deploy_maven:
    executor: java-8
    steps:
      - restore_workspace
      - gradle_cache
      - run: ./gradlew pickle-processor:publish
      - run: ./gradlew pickle-lib:publish
  deply_gradle_plugin:
    executor: java-8
    steps:
      - restore_workspace
      - gradle_cache
      - run: ./gradlew pickle-plugin:publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
workflows:
  version: 2
  build-test:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - assemble_samples:
          requires:
            - build
      - test:
          requires:
            - build
      - static_analysis:
          requires:
            - build
  build-deploy:
    jobs:
      - checkout:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build:
          requires:
            - checkout
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deply_gradle_plugin:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
